### ISSUE TITLE
Glive repository issue

### ISSUE THREAD

**Issue by faeezhoosein** [mrgsi/mrgsi.github.io#10]
TvOne112 does not work, is there perhaps a fix for it.

**Comment by mrgsi** [comment]
It's working on my PC. What is doing? Not loading? Did you try different links? It's not uncommon for some links to break. You can also try going into setting and change the stream plugin to inputstream.adaptive. Also, what Kodi version are you using?

**Comment by faeezhoosein** [comment]
My Kodi version is 20.2 and I have changed the stream plugin to inputstream.adaptive but still no luck. Is there perhaps anything else I should try, I really loved having this link. Thank you in advance and keep up the good work!!! 🙂
