### ISSUE TITLE
The TV app

### ISSUE THREAD

**Issue by Shoninzo** [mrgsi/mrgsi.github.io#11]
The TV app isn't working

**Comment by mrgsi** [comment]
Yes, it's not working for me either. This happened before but resolved itself. I can't see what the issue is myself. It's an unsupported add-on but in a lot of repos so I will keep an eye out for an update.

**Comment by Shoninzo** [comment]
Just wanted to let you know that the diggz repo updated the TV app addon

**Comment by mrgsi** [comment]
Got it! Thanks for the heads up!

**Comment by Shoninzo** [comment]
The problem is that the original developers of the site keep changing the streaming encryption
