### ISSUE TITLE
Addon Players

### ISSUE THREAD

**Issue by joexp203** [mrgsi/mrgsi.github.io#12]
Hey there! I was just wondering if you could when you get free time to add these two addons to the moviedb helper players list.

-The Promise 
-Twilight

Thanks!

**Comment by mrgsi** [comment]
They are now available. Twilight has 2 players (source select and autoplay). I re-added ThePromise but you should know, that add-on has been abandoned by the developer Tech E Coyote. He rebuilt it as "The Lab" which is in his new repo. His repository can be installed from https://th3l48.github.io/TheLab Another one is Homelander from the Crew repo which is a "The Oath" fork just like ThePromise but with a slightly different menu. ThePromise should continue to work as is but some links will be broken as it was coded to work from a repository that no longer exists.

**Comment by joexp203** [comment]
Wow! You are the greatest! Thank you a lot for adding them! I greatly appreciate it. And probably more people will as well!
