### ISSUE TITLE
The TV app addon not working again 

### ISSUE THREAD

**Issue by Shoninzo** [mrgsi/mrgsi.github.io#13]
I found a way around the TV app addon not working, it's working fine through the gratis video addon from funstersplace repo

**Comment by mrgsi** [comment]
Updated to version 0.4. Lets see how long this one lasts. lol

**Comment by Shoninzo** [comment]
The problem was that the developers of the actual TV app kept changing the streaming encryption

**Comment by Shoninzo** [comment]
The TV app addon has been updated to 420.9 in the diggz repo
