### ISSUE TITLE
Problems with Tvone 11,111,112,and 1112.

### ISSUE THREAD

**Issue by Greg0580** [mrgsi/mrgsi.github.io#6]
I just want ti let you know that tvone 11. Is having server errors .
And TVone 111,112,1112. Alot of the USA,Canada and Australian,  channels. Keep showing playback failed message. For about a week now. Especially HGTV us,can, and 502 fox sports Australia just to mention a few. I Don't know if you can clear there Cache at Your end or not or you can do anything.  All I want is to inform you in case you get others complaining.  I know in a lot cases there nothing you can do.

**Comment by mrgsi** [comment]
Not surprising as free IPTV is very unstable and even worse if the developer isn't doing weekly checks and updates. The RACC developer for all the tvOne add-ons is in China so there isn't much we can do until he drops some new updates. It's been a while so these could be dead in the water. I'm still checking the source in case new versions come out. MegaIPTV on the other hand uses links that are continuously updated.

**Comment by Greg0580** [comment]
Thank you  for your quick reply.  And I will check it out.   You only can what you can do. And I appreciate that. When l see people asking for Live tv and  live sports . I recommend your site. As it only for Live sports and Live tv.  Have a Good day.



Sent from my Galaxy



-------- Original message --------
From: G-Man ***@***.***>
Date: 28/11/22 15:30 (GMT+12:00)
To: "mrgsi/mrgsi.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [mrgsi/mrgsi.github.io] Problems with Tvone 11,111,112,and 1112. (Issue #6)


Not surprising as free IPTV is very unstable and even worse if the developer isn't doing weekly checks and updates. The RACC developer for all the tvOne add-ons is in China so there isn't much we can do until he drops some new updates. It's been a while so these could be dead in the water. I'm still checking the source in case new versions come out. MegaIPTV on the other hand uses links that are continuously updated.

**Comment by mrgsi** [comment]
tvOne add-ons have been updated with the dates of their last version update included in their descriptions.
