### ISSUE TITLE
G source, Repositories 

### ISSUE THREAD

**Issue by Greg0580** [mrgsi/mrgsi.github.io#9]
Hi G Man.
I see you have The Warehouse and the Lab Repositories in your Repos sections 
The Warehouse has been removed from github and The Lab New source  is https://th3l48.github.io/TheLab
It was only updated to the above in the last few days.  And it works on kodi 18/19/20 And kodi 21 Alpha 3.

**Comment by mrgsi** [comment]
Ah, thank you I've been looking for it's new home. I didn't think Tech E would disappear that quickly he's put too much work into it. He is a Wile E Coyote. lol

**Comment by Greg0580** [comment]
Allgood.  Glade to help. If you every decide to add tidal so you can open your tidal account in it and eg play Dolby Atmos music through it. And or Amazon, Spotify, Apple music.  
I  would use at least one of them.
If not all good Just an idea.  I just like Dolby Atmos music.

**Comment by mrgsi** [comment]
Never heard of Tidal before, but looks interesting so I've added it to G-Scribe, my subscription add-ons repo.
